config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'coaching#ask'

  get 'answer', to: 'coaching#answer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def ask
  end

  def answer
    @question = params["query"].capitalize
    if @question.end_with?("?")
      @answer = "Silly question, get dressed and go to work!"
    elsif @question == "I am going to work right now!"
      @answer = ""
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<div style="text-align: center">
  <div style="padding: 30px"></div>
  <h2> <%= @question %> </h2>
  <p> - You </p>
  <div style="padding: 30px"></div>
  <h2> <%= @answer %> </h2>
  <p> - Coach </p>
  <div style="padding: 30px"></div>
  <%= link_to "Ask a new question", ask_path %>
</div>

app/views/coaching/ask.html.erb
<div style="text-align: center">
  <form action="/answer">
    <label for="question">Speak to your coach</label>
    <input type="text" id="question" name="query" placeholder="what time is it?">
    <input type="submit" value="Go on!">
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>